services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jp-hacks-expo
    env_file:
      - .env
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -lc "npx expo start --lan --clear"
    tty: true
    stdin_open: true

