import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../../styles/theme';

const { width } = Dimensions.get('window');

export const RandomStyles = StyleSheet.create({
  container: {
    flex: 1,
    position: 'relative',
  },
  backgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 12,
    alignItems: 'center',
    backgroundColor: 'transparent',
    flexGrow: 1,
  },
  header: {
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: 10,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    width: '100%',
    paddingHorizontal: 20,
    position: 'relative',
  },
  personAddIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    backgroundColor: 'transparent',
    position: 'absolute',
    left: 20,
  },
  logoImage: {
    width: 200,
    height: 50,
    resizeMode: 'contain',
    backgroundColor: 'transparent',
    tintColor: undefined,
  },
  contentArea: {
    width: '100%',
    alignItems: 'center',
    marginTop: 30,
  },
  mainCard: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  cardHeader: {
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1A33A5',
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 16,
    color: '#666',
    lineHeight: 22,
  },
  cardContent: {
    alignItems: 'center',
  },
  cardImage: {
    width: '100%',
    height: 200,
    borderRadius: 15,
    marginBottom: 20,
  },
  cardButton: {
    backgroundColor: '#1A33A5',
    paddingHorizontal: 30,
    paddingVertical: 12,
    borderRadius: 25,
  },
  cardButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  profileButton: {
    position: 'absolute',
    top: 39,
    right: 18,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
    zIndex: 1002,
  },
  profileButtonImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  pillWrap: {
    marginTop: 18,
    width: '100%',
    alignItems: 'center',
    zIndex: 1000,
  },
  pill: {
    width: 200,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 6,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    overflow: 'hidden',
    position: 'relative',
    zIndex: 1001,
  },
  pillGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 30,
  },
  animatedIndicator: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#fff',
    left: 76,
    top: 6,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
    zIndex: 10,
  },
  ripple: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.2)',
    left: 76,
    top: 6,
    zIndex: 5,
  },
  pillSmallIcon: {
    position: 'absolute',
    width: 24,
    height: 24,
    top: 14,
    tintColor: '#fff',
    opacity: 0.6,
    zIndex: 2,
  },
  indicatorIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    // ensure the icon is perfectly centered inside the indicator
    alignSelf: 'center',
  },
  pillIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pillIconWrapActiveHome: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#3b82f6',
    shadowColor: '#3b82f6',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  pillIconWrapActiveFriend: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#fb923c',
    shadowColor: '#fb923c',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  pillIcon: {
    fontSize: 18,
  },
  pillSide: {
    flex: 1,
    height: '100%',
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pillSideActive: {
    backgroundColor: 'transparent',
  },
  pillFriendBackground: {
    backgroundColor: '#ffdca8',
  },
  sectionShadow: {
    marginTop: 18,
    width: '100%',
    alignItems: 'center',
  },
  waveTop: {
    width: '100%',
    height: 22,
    backgroundColor: '#bee0ff',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: -6,
  },
  card: {
    width: width - 40,
    height: 220,
    backgroundColor: '#e6f4ff',
    marginTop: -12,
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  cardImageInner: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    resizeMode: 'cover',
    opacity: 0.95,
  },
  waveBottom: {
    width: '100%',
    height: 26,
    backgroundColor: '#bee0ff',
    marginTop: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  profileCard: {
    marginTop: 24,
    width: width - 40,
    backgroundColor: '#eaf8ff',
    padding: 12,
    borderRadius: 12,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  smallAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#fff',
    marginBottom: 8,
  },
  profileImageWrap: {
    width: '100%',
    height: 180,
    backgroundColor: '#dbeafe',
    borderRadius: 10,
    overflow: 'hidden',
  },
  profileImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
});
