import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../../styles/theme';

const { width } = Dimensions.get('window');

export const RandomStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1e90ff',
  },
  scrollContent: {
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  header: {
    marginTop: 6,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    fontSize: 36,
    fontWeight: '900',
    color: '#1730a3',
    letterSpacing: 1,
    textShadowColor: 'rgba(0,0,0,0.15)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  logoImage: {
    width: 220,
    height: 48,
    resizeMode: 'contain',
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    position: 'absolute',
    right: 16,
    top: 0,
    borderWidth: 2,
    borderColor: '#fff',
  },
  pillWrap: {
    marginTop: 18,
    width: '100%',
    alignItems: 'center',
  },
  pill: {
    width: 170,
    height: 52,
    borderRadius: 40,
    backgroundColor: '#e9f2ff',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 4,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  animatedIndicator: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#fff',
    left: 61,
    top: 4,
    justifyContent: 'center',
    alignItems: 'center',
    // shadow to match active state
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
    zIndex: 10,
  },
  ripple: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.14)',
    left: 61,
    top: 4,
    zIndex: 5,
  },
  pillSmallIcon: {
    position: 'absolute',
    width: 24,
    height: 24,
    top: 14,
    tintColor: '#fff',
    opacity: 0.6,
    zIndex: 2,
  },
  indicatorIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    // ensure the icon is perfectly centered inside the indicator
    alignSelf: 'center',
  },
  pillIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pillIconWrapActiveHome: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#3b82f6',
    shadowColor: '#3b82f6',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  pillIconWrapActiveFriend: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#fb923c',
    shadowColor: '#fb923c',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  pillIcon: {
    fontSize: 18,
  },
  pillSide: {
    flex: 1,
    height: '100%',
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pillSideActive: {
    backgroundColor: 'transparent',
  },
  pillFriendBackground: {
    backgroundColor: '#ffdca8',
  },
  sectionShadow: {
    marginTop: 18,
    width: '100%',
    alignItems: 'center',
  },
  waveTop: {
    width: '100%',
    height: 22,
    backgroundColor: '#bee0ff',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: -6,
  },
  card: {
    width: width - 40,
    height: 220,
    backgroundColor: '#e6f4ff',
    marginTop: -12,
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    resizeMode: 'cover',
    opacity: 0.95,
  },
  waveBottom: {
    width: '100%',
    height: 26,
    backgroundColor: '#bee0ff',
    marginTop: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  profileCard: {
    marginTop: 24,
    width: width - 40,
    backgroundColor: '#eaf8ff',
    padding: 12,
    borderRadius: 12,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  smallAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#fff',
    marginBottom: 8,
  },
  profileImageWrap: {
    width: '100%',
    height: 180,
    backgroundColor: '#dbeafe',
    borderRadius: 10,
    overflow: 'hidden',
  },
  profileImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
});
